volumes:
  db_data:

services:
  php:
    container_name: "phalcrud-php"
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        PHALCON_VERSION: 5.2.1
        PSR_VERSION: 1.2.0
        PHP_VERSION: 8.1.29
    restart: unless-stopped
    environment:
      XDEBUG_CONFIG: discover_client_host=1 client_host=host.docker.internal client_port=9003
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
      - ./docker/php/logs:/var/log/php

  nginx:
    container_name: "phalcrud-nginx"
    build: ./docker/nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: "phalcrud-db"
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/schema:/docker-entrypoint-initdb.d
