<?php declare(strict_types=1);
echo Phalcon\Tag::formLegacy(['action' => 'signup/register', 'class' => 'form']); ?>

<fieldset class="form-group">
  <label for="name">nombre</label>
  <?php echo Phalcon\Tag::textField(['name', 'class' => 'form-control']); ?>
</fieldset>

<fieldset class="form-group">
  <label for="email">correo</label>
  <?php echo Phalcon\Tag::textField(['email', 'class' => 'form-control']); ?>
</fieldset>

<fieldset class="form-group">
  <label for="pass">contraseña</label>
  <?php echo Phalcon\Tag::textField(['pass', 'class' => 'form-control']); ?>
</fieldset>

<div class="form-actions">
  <?php echo Phalcon\Tag::submitButton(['registrar', 'class' => 'btn btn-primary btn-block']); ?>
</div>

<?php echo Phalcon\Tag::endForm(); ?>

<?php echo Phalcon\Tag::linkTo(['/', 'atrás', 'class' => 'btn btn-primary']); ?>