<?php

declare(strict_types=1);

/** @var $users App\Models\User */
if ($users->count() > 0) { ?>
  <hr class="my-3">
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>#</th>
        <th>nombre</th>
        <th>correo</th>
        <th>contraseña</th>
        <th>acciones</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($users as $user) { ?>
        <tr>
          <td><?php echo $user->id; ?></td>
          <td><?php echo $user->name; ?></td>
          <td><?php echo $user->email; ?></td>
          <td><?php echo $user->pass; ?></td>
          <td>
            <?php echo Phalcon\Tag::linkTo(['edit?id=' . $user->id, 'editar', 'class' => 'btn btn-warning']); ?>
            <?php echo Phalcon\Tag::linkTo(['delete?id=' . $user->id, 'eliminar', 'class' => 'btn btn-error']); ?>
          </td>
        </tr>
      <?php } ?>
    </tbody>
  </table>
<?php
} else { ?>
  <div class="alert alert-info" role="alert">
    no hay usuarios registrados
  </div>
<?php
}

echo Phalcon\Tag::linkTo(['signup', 'agregar usuario', 'class' => 'btn btn-primary']);
?>