<!doctype html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <title>CRUD</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hack/0.8.1/hack.css" integrity="sha512-aKs7+Z3okpWvDV412JxbJDBGnC0i4GbFEH1VAYimNMdbOV9skiE3qyQpeWdI0jVW6HF0MsBUiewSjEqHt2M9Cg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body class="hack">
  <div class=" container">
    <h1>Phalcrud</h1>

    <?php echo $this->getContent(); ?>
  </div>
</body>

</html>