<?php declare(strict_types=1);
echo Phalcon\Tag::formLegacy(['action' => 'edit/update', 'class' => 'form']); ?>
<?php echo Phalcon\Tag::hiddenField(['id', 'value' => $user->id]); ?>

<fieldset class="form-group">
  <label for="name">nombre</label>
  <?php echo Phalcon\Tag::textField(['name', 'value' => $user->name, 'class' => 'form-control']); ?>
</fieldset>

<fieldset class="form-group">
  <label for="email">correo</label>
  <?php echo Phalcon\Tag::textField(['email', 'value' => $user->email, 'class' => 'form-control']); ?>
</fieldset>

<fieldset class="form-group">
  <label for="pass">contraseña</label>
  <?php echo Phalcon\Tag::textField(['pass', 'value' => $user->pass, 'class' => 'form-control']); ?>
</fieldset>

<div class="form-actions">
  <?php echo Phalcon\Tag::submitButton(['actualizar', 'class' => 'btn btn-primary btn-block']); ?>
</div>

<?php echo Phalcon\Tag::endForm(); ?>
<?php echo Phalcon\Tag::linkTo(['/', 'atrás', 'class' => 'btn btn-primary']); ?>